In [128]:
import pandas as pd

In [129]:
all_posts = pd.read_csv("posts.csv")

In [130]:
text = all_posts[["Created On", "Post Text"]]
text.columns = ["Date", "Text"]
text.Date = pd.to_datetime(text.Date)
text['Date'] = text['Date']

/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/1984149365.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text.Date = pd.to_datetime(text.Date)
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/1984149365.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text['Date'] = text['Date']

In [131]:
text["Tariff"] = text.Text.str.contains(
    r"\b(tariff|tariffs|trade war|import tax|export tax|customs duties|trade barrier|trade sanctions|import restrictions|tariff hike|retaliatory tariffs|tariff exemption)\b", 
    case=False, regex=True) * 1

/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/75052436.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["Tariff"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/75052436.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["Tariff"] = text.Text.str.contains(

In [132]:
text["AAPL"] = text.Text.str.contains(
    r"\b(apple|aapl|iphone sales|mac sales|apple earnings|apple stock|apple revenue|apple profit|tim cook|apple forecast|iphone demand|apple supply chain|apple lawsuit|apple buyback|apple dividend)\b", 
    case=False, regex=True) * 1

text["TSLA"] = text.Text.str.contains(
    r"\b(tesla|tsla|elon musk|tesla earnings|tesla stock|tesla deliveries|tesla production|model 3 sales|cybertruck|tesla gigafactory|tesla lawsuit|tesla price cut|autopilot investigation)\b", 
    case=False, regex=True) * 1

text["META"] = text.Text.str.contains(
    r"\b(meta|facebook|meta earnings|fb stock|instagram revenue|meta layoffs|metaverse investment|oculus sales|meta advertising slowdown|meta regulation|whatsapp growth)\b", 
    case=False, regex=True) * 1

text["AMZN"] = text.Text.str.contains(
    r"\b(amazon|amzn|aws growth|amazon earnings|amazon prime memberships|amazon stock|amazon layoffs|amazon labor strike|amazon revenue forecast|amazon advertising)\b", 
    case=False, regex=True) * 1

text["NVDA"] = text.Text.str.contains(
    r"\b(nvidia|nvda|nvidia earnings|nvidia stock|nvidia ai chips|gpu sales|h100 demand|nvidia supply chain|nvidia lawsuit|semiconductor boom|ai chip market)\b", 
    case=False, regex=True) * 1

text["Tech"] = text.Text.str.contains(
    r"\b(tech sector|technology stocks|semiconductor shortage|ai boom|it sector growth|tech layoffs|software spending|hardware demand|cloud growth|cybersecurity threat)\b", 
    case=False, regex=True) * 1

text["Consumer"] = text.Text.str.contains(
    r"\b(consumer spending|retail sales|consumer sentiment|e-commerce boom|holiday shopping|inflation impact on consumers|consumer goods demand|consumer discretionary sector|consumer)\b", 
    case=False, regex=True) * 1

text["Com"] = text.Text.str.contains(
    r"\b(communication services sector|telecom growth|social media ad revenue|messaging app expansion|internet services growth|wireless carrier competition|communication)\b", 
    case=False, regex=True) * 1

text["Tariff"] = text.Text.str.contains(
    r"\b(tariff|tariffs|trade war|import tax|export tax|customs duties|trade barrier|trade sanctions|import restrictions|tariff hike|retaliatory tariffs|tariff exemption)\b", 
    case=False, regex=True) * 1

/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["AAPL"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["AAPL"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["TSLA"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["TSLA"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["META"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["META"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["AMZN"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["AMZN"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["NVDA"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["NVDA"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:21: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["Tech"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text["Tech"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:25: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["Consumer"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:29: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["Com"] = text.Text.str.contains(
/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/544861371.py:33: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  text["Tariff"] = text.Text.str.contains(

In [133]:
text.dropna(inplace = True)

In [134]:
for col in ["AAPL", "TSLA", "META", "AMZN", "NVDA", "Tech", "Consumer", "Com"]:
    print(text[col].sum())

79
130
35
48
98
8
75
3

In [135]:
import re
text['Text'] = text['Text'].apply(lambda x: re.sub(r'http\S+|www\S+', '', x))
text['Text'] = text['Text'].str.replace(r'[^A-Za-z\s]', '', regex=True)
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    token_pattern=r'\b[a-zA-Z]{2,}\b'
)

tfidf_matrix = vectorizer.fit_transform(text['Text'].fillna(''))
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [136]:
tfidf_df.index = text.Date

In [137]:
tfidf_df = tfidf_df.reset_index()

In [138]:
tfidf_df.Date = tfidf_df.Date.dt.date

In [139]:
day_sum  = tfidf_df.groupby("Date").sum()

In [140]:
text_day = text.drop(columns="Text")
text_day.Date = text_day.Date.dt.date
text_day = text_day.groupby("Date").sum()

In [141]:
text_day['tfidf_sum'] = day_sum.sum(axis=1)
text_day['tfidf_mean'] = day_sum.mean(axis=1)
text_day['tfidf_max'] = day_sum.max(axis=1)
important_words = ['growth', 'inflation', 'profit', 'revenue', 'rate', 'debt', 'earnings', 'guidance', 'market', 'forecast', 'downgrade', 'upgrade']
existing_words = [word for word in important_words if word in day_sum.columns]
text_day['important_words_sum'] = day_sum[existing_words].sum(axis=1)
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()
text['sentiment'] = text['Text'].fillna('').apply(lambda x: sia.polarity_scores(x)['compound'])

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/sophialin/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [142]:
text_day

,Tariff,AAPL,TSLA,META,AMZN,NVDA,Tech,Consumer,Com,tfidf_sum,tfidf_mean,tfidf_max,important_words_sum
Date,,,,,,,,,,,,,
2025-04-02,0,0,0,0,0,0,0,0,0,22.206731,0.001315,0.358558,0.135382
2025-04-03,14,6,2,0,3,3,0,4,0,309.710915,0.018338,1.797681,2.002459
2025-04-04,23,2,3,0,2,5,0,1,0,490.655690,0.029052,3.821099,6.776986
2025-04-05,12,0,1,0,0,0,0,0,0,369.924394,0.021903,2.640757,4.597999
2025-04-06,13,1,1,0,1,3,0,1,0,286.894383,0.016987,2.491486,3.613421
2025-04-07,23,3,4,2,0,4,1,3,1,675.600334,0.040002,4.626654,8.101186
2025-04-08,57,4,9,0,3,5,2,3,0,974.309203,0.057689,5.704408,10.721739
2025-04-09,110,17,8,5,10,16,0,9,0,1689.919530,0.100060,10.087887,18.029879
2025-04-10,56,2,7,2,2,1,0,3,0,1002.172822,0.059339,6.723789,12.760956
2025-04-11,38,1,10,1,1,3,0,6,0,753.682721,0.044626,4.080154,8.995517
2025-04-12,20,5,2,0,1,3,0,3,1,442.146454,0.026180,2.102252,4.598525
2025-04-13,36,7,4,1,1,4,0,4,0,551.458665,0.032652,3.101397,6.096165
2025-04-14,25,5,2,0,3,6,0,3,0,581.477359,0.034429,2.485697,6.434243
2025-04-15,27,5,3,2,2,3,0,5,0,625.814958,0.037055,2.844255,7.524449
2025-04-16,26,1,4,4,1,13,1,2,0,672.202251,0.039801,3.058785,7.181348
2025-04-17,29,6,5,2,2,5,0,2,0,709.184964,0.041991,2.614426,8.227624
2025-04-18,17,2,2,2,1,2,0,6,0,466.857633,0.027643,1.964080,5.445668
2025-04-19,16,2,2,2,1,2,0,4,0,374.217069,0.022157,1.726575,4.057071
2025-04-20,7,0,5,1,1,2,0,1,1,220.839949,0.013076,1.313179,1.377589
2025-04-21,25,1,11,0,2,2,0,3,0,650.551184,0.038519,3.135473,8.381278
2025-04-22,26,0,14,0,0,1,0,3,0,597.282409,0.035365,2.379333,7.947533
2025-04-23,34,4,11,4,2,7,0,2,0,646.012346,0.038250,2.848239,8.298187
2025-04-24,30,2,11,4,5,3,2,5,0,737.049198,0.043641,3.387011,11.573838
2025-04-25,12,2,7,3,4,5,2,2,0,558.062832,0.033043,3.329808,7.599477
2025-04-26,4,1,2,0,0,0,0,0,0,190.938009,0.011305,0.942880,1.773932

In [158]:
selected = all_posts[["Created On", "Score", "Upvote Ratio", "Total Comments"]]
selected["sentiment"] = text.sentiment

/var/folders/w_/wzxdnvq13mxbxkhjgg1mty_80000gn/T/ipykernel_75163/2510585625.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected["sentiment"] = text.sentiment

In [160]:
selected.rename({"Created On" : "Date"}, axis = 1, inplace= True)
selected = selected.dropna()
selected.Date = pd.to_datetime(selected.Date).dt.date

In [162]:
# Step 1: Compute weighted sentiment
selected["weighted_sentiment"] = selected["sentiment"] * selected["Score"]

# Step 2: Compute weighted average sentiment per day
weighted_sentiment = selected.groupby("Date").apply(
    lambda x: x["weighted_sentiment"].sum() / x["Score"].sum() if x["Score"].sum() > 0 else 0
).reset_index(name="Weighted Sentiment")

# Step 3: Basic daily aggregation
daily_summary = selected.groupby("Date").agg({
    "Score": "sum",
    "Upvote Ratio": "mean",
    "Total Comments": "sum"
}).reset_index()

# Step 4: Add post count
daily_summary["Post Count"] = selected.groupby("Date").size().values

# Step 5: Merge weighted sentiment into summary
daily_summary = daily_summary.merge(weighted_sentiment, on="Date", how="left")

In [163]:
daily_summary

,Date,Score,Upvote Ratio,Total Comments,Post Count,Weighted Sentiment
0,2025-04-02,118,0.683333,277,3,0.396579
1,2025-04-03,10586,0.538776,3261,49,0.188790
2,2025-04-04,20857,0.611585,8105,82,-0.233472
3,2025-04-05,4649,0.550678,3427,59,-0.603229
4,2025-04-06,21358,0.655918,37933,49,-0.037846
5,2025-04-07,70486,0.679040,71490,125,0.201007
6,2025-04-08,52700,0.687317,94002,164,-0.164746
7,2025-04-09,287061,0.735760,122903,283,0.191455
8,2025-04-10,118086,0.729441,80415,179,0.273054
9,2025-04-11,60240,0.709839,72317,124,-0.281145
10,2025-04-12,49157,0.710519,13288,77,0.051106
11,2025-04-13,64803,0.726897,27833,87,-0.064099
12,2025-04-14,54378,0.750606,41733,99,0.002602
13,2025-04-15,30830,0.722549,45049,102,-0.137636
14,2025-04-16,99052,0.800926,58253,108,-0.184295
15,2025-04-17,93884,0.759910,43905,111,-0.257804
16,2025-04-18,59696,0.761857,27363,70,-0.004733
17,2025-04-19,28949,0.716200,5572,50,-0.203633
18,2025-04-20,15457,0.726562,15654,32,0.333237
19,2025-04-21,79982,0.757857,51734,112,-0.208296
20,2025-04-22,89167,0.793500,54710,100,-0.001421
21,2025-04-23,97074,0.766724,47519,116,-0.146104
22,2025-04-24,143390,0.766083,46040,120,0.303298
23,2025-04-25,29728,0.721562,32271,96,0.026467
24,2025-04-26,3737,0.764138,1190,29,0.403366

In [164]:
features = pd.merge(daily_summary, text_day, on = "Date", how = "left")

In [165]:
features

,Date,Score,Upvote Ratio,Total Comments,Post Count,Weighted Sentiment,Tariff,AAPL,TSLA,META,AMZN,NVDA,Tech,Consumer,Com,tfidf_sum,tfidf_mean,tfidf_max,important_words_sum
0,2025-04-02,118,0.683333,277,3,0.396579,0,0,0,0,0,0,0,0,0,22.206731,0.001315,0.358558,0.135382
1,2025-04-03,10586,0.538776,3261,49,0.188790,14,6,2,0,3,3,0,4,0,309.710915,0.018338,1.797681,2.002459
2,2025-04-04,20857,0.611585,8105,82,-0.233472,23,2,3,0,2,5,0,1,0,490.655690,0.029052,3.821099,6.776986
3,2025-04-05,4649,0.550678,3427,59,-0.603229,12,0,1,0,0,0,0,0,0,369.924394,0.021903,2.640757,4.597999
4,2025-04-06,21358,0.655918,37933,49,-0.037846,13,1,1,0,1,3,0,1,0,286.894383,0.016987,2.491486,3.613421
5,2025-04-07,70486,0.679040,71490,125,0.201007,23,3,4,2,0,4,1,3,1,675.600334,0.040002,4.626654,8.101186
6,2025-04-08,52700,0.687317,94002,164,-0.164746,57,4,9,0,3,5,2,3,0,974.309203,0.057689,5.704408,10.721739
7,2025-04-09,287061,0.735760,122903,283,0.191455,110,17,8,5,10,16,0,9,0,1689.919530,0.100060,10.087887,18.029879
8,2025-04-10,118086,0.729441,80415,179,0.273054,56,2,7,2,2,1,0,3,0,1002.172822,0.059339,6.723789,12.760956
9,2025-04-11,60240,0.709839,72317,124,-0.281145,38,1,10,1,1,3,0,6,0,753.682721,0.044626,4.080154,8.995517
10,2025-04-12,49157,0.710519,13288,77,0.051106,20,5,2,0,1,3,0,3,1,442.146454,0.026180,2.102252,4.598525
11,2025-04-13,64803,0.726897,27833,87,-0.064099,36,7,4,1,1,4,0,4,0,551.458665,0.032652,3.101397,6.096165
12,2025-04-14,54378,0.750606,41733,99,0.002602,25,5,2,0,3,6,0,3,0,581.477359,0.034429,2.485697,6.434243
13,2025-04-15,30830,0.722549,45049,102,-0.137636,27,5,3,2,2,3,0,5,0,625.814958,0.037055,2.844255,7.524449
14,2025-04-16,99052,0.800926,58253,108,-0.184295,26,1,4,4,1,13,1,2,0,672.202251,0.039801,3.058785,7.181348
15,2025-04-17,93884,0.759910,43905,111,-0.257804,29,6,5,2,2,5,0,2,0,709.184964,0.041991,2.614426,8.227624
16,2025-04-18,59696,0.761857,27363,70,-0.004733,17,2,2,2,1,2,0,6,0,466.857633,0.027643,1.964080,5.445668
17,2025-04-19,28949,0.716200,5572,50,-0.203633,16,2,2,2,1,2,0,4,0,374.217069,0.022157,1.726575,4.057071
18,2025-04-20,15457,0.726562,15654,32,0.333237,7,0,5,1,1,2,0,1,1,220.839949,0.013076,1.313179,1.377589
19,2025-04-21,79982,0.757857,51734,112,-0.208296,25,1,11,0,2,2,0,3,0,650.551184,0.038519,3.135473,8.381278
20,2025-04-22,89167,0.793500,54710,100,-0.001421,26,0,14,0,0,1,0,3,0,597.282409,0.035365,2.379333,7.947533
21,2025-04-23,97074,0.766724,47519,116,-0.146104,34,4,11,4,2,7,0,2,0,646.012346,0.038250,2.848239,8.298187
22,2025-04-24,143390,0.766083,46040,120,0.303298,30,2,11,4,5,3,2,5,0,737.049198,0.043641,3.387011,11.573838
23,2025-04-25,29728,0.721562,32271,96,0.026467,12,2,7,3,4,5,2,2,0,558.062832,0.033043,3.329808,7.599477
24,2025-04-26,3737,0.764138,1190,29,0.403366,4,1,2,0,0,0,0,0,0,190.938009,0.011305,0.942880,1.773932